### ISSUE TITLE
Add a "Build release zip" GitHub Action

### ISSUE THREAD

**Issue by iamdharmesh** [observermedia/eight-day-week#104]
### Is your enhancement related to a problem? Please describe.

- [ ] Add "Build release zip" GitHub Action to generate the release zip before the actual release. 
- [ ] Release Instructions are updated to test generated zip before shipping the release.

Reference PR: https://github.com/10up/autoshare-for-twitter/pull/201

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jayedul** [comment]
@iamdharmesh  It looks like the build release action is added already. And even we've introduced e2e test on built zip in this PR https://github.com/10up/eight-day-week/pull/113

**Comment by iamdharmesh** [comment]
Thanks for the note @jayedul.
