### ISSUE TITLE
Update code to conform to WP coding standards

### ISSUE THREAD

**Issue by bmarshall511** [observermedia/eight-day-week#118]
### Is your enhancement related to a problem? Please describe.

Creating this to better track the progress of updating the code to better comply with WP coding standards, see https://github.com/10up/eight-day-week/pull/117#issuecomment-1587677103

* Update (6/28/23) - The remaining items left are a little more involved, see https://github.com/10up/eight-day-week/issues/118#issuecomment-1591666342

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bmarshall511** [comment]
👋 @jeffpaul @peterwilsoncc, I've tackled most of the coding standards issues 🛠️, but there are still a few left concerning hook names using slashes vs. underscores. I'm a bit hesitant to make these updates, as others might be utilizing those hooks in their implementations and I don't want to accidentally break anything 😅. Additionally, there's quite a bit to address regarding processing form data without nonce verification. It seems like that will require more extensive work than just updating a few lines, so it might be better to handle it through a separate issue. Let me know what you all think. 💭

**Comment by jeffpaul** [comment]
@bmarshall511 splitting out the different concerns into separate PRs should help ensure the "easy" ones get out quickly while any deeper conversations only hold up the more "complex" updates

**Comment by bmarshall511** [comment]
Sounds good @jeffpaul! I went ahead and submitted a PR for the first round of the easy ones 👆 Once reviewed & merged, do you wanna keep this open to track the harder ones or open a new issue?

**Comment by jeffpaul** [comment]
@bmarshall511 fine to keep this one open or open a subsequent one with specifics on the more complex updates, dealers choice.

**Comment by bmarshall511** [comment]
@jeffpaul Sounds good, I'll just leave this open & updated the desc. Running the linter should provide enough specifics of what's remaining.
