### ISSUE TITLE
Refresh POT file

### ISSUE THREAD

**Issue by jeffpaul** [observermedia/eight-day-week#53]
**Is your enhancement related to a problem? Please describe.**
After releasing v1.1.1 and checking the [translations on .org](https://translate.wordpress.org/projects/wp-plugins/eight-day-week-print-workflow/), I noticed that some of the [strings to be translated](https://github.com/10up/eight-day-week/blob/develop/languages/eight-day-week-print-workflow.pot) could be merged together given how similar they are or did not appear to need translations.

**Describe the solution you'd like**

Possibly remove?
- [ ] https://github.com/10up/eight-day-week/blob/e7f0000c80ecc045131942f5dfe43ffb27936822/languages/eight-day-week-print-workflow.pot#L425
- [ ] https://github.com/10up/eight-day-week/blob/e7f0000c80ecc045131942f5dfe43ffb27936822/languages/eight-day-week-print-workflow.pot#L429

I believe core removed this message in a recent release, we might update accordingly
- [x] https://github.com/10up/eight-day-week/blob/e7f0000c80ecc045131942f5dfe43ffb27936822/languages/eight-day-week-print-workflow.pot#L413

Possibly merge?
- [ ] https://github.com/10up/eight-day-week/blob/e7f0000c80ecc045131942f5dfe43ffb27936822/languages/eight-day-week-print-workflow.pot#L22 && https://github.com/10up/eight-day-week/blob/e7f0000c80ecc045131942f5dfe43ffb27936822/languages/eight-day-week-print-workflow.pot#L299
- [ ] https://github.com/10up/eight-day-week/blob/e7f0000c80ecc045131942f5dfe43ffb27936822/languages/eight-day-week-print-workflow.pot#L39 && https://github.com/10up/eight-day-week/blob/e7f0000c80ecc045131942f5dfe43ffb27936822/languages/eight-day-week-print-workflow.pot#L332
- [ ] https://github.com/10up/eight-day-week/blob/e7f0000c80ecc045131942f5dfe43ffb27936822/languages/eight-day-week-print-workflow.pot#L43 && https://github.com/10up/eight-day-week/blob/e7f0000c80ecc045131942f5dfe43ffb27936822/languages/eight-day-week-print-workflow.pot#L356

**Designs**

n/a

**Describe alternatives you've considered**

none

**Additional context**

n/a

**Comment by helen** [comment]
Beyond the contents of the strings, I don't think we need to actually include the POT file ourselves anymore? So if this is working in Rosetta now I think we can actually delete the entire `languages` dir.
