### ISSUE TITLE
Can't open exported zip archive because it's "invalid"

### ISSUE THREAD

**Issue by FlorianBrinkmann** [observermedia/eight-day-week#6]
Hi!
Today I tested your plugin to write an article about it but I can't unzip the archive with the XML file for InDesign… I get an error, that the "zip file is invalid" (I'm on Windows 10 if it's important).
I use WordPress 4.5-alpha-35853.

**Comment by cwright503** [comment]
Hi Florian,

Thanks for reporting this issue. I have a hunch that this is a similar to #5. Any chance that you can get a server log to confirm that you're getting the same error?

**Comment by FlorianBrinkmann** [comment]
Hi @cwright503,

yes, I have a server log but there are no errors relating to the plugin… And the zip file is downloaded without problems into my downloads folder, I “only” can't open it.
But in Firefox I get the message “Whoops! Looks like this page has been sitting for a while. Try refreshing!” after hitting the “Export all” button (but the zip file is downloaded nevertheless).
I have attached the exported zip to this post, maybe it helps?

[Issue t3n Nr. 40 - Wachstum mit Werten exported on 01-12-16 at 07_28pm.zip](https://github.com/observermedia/eight-day-week/files/87785/Issue.t3n.Nr.40.-.Wachstum.mit.Werten.exported.on.01-12-16.at.07_28pm.zip)

**Comment by sternb0t** [comment]
Interesting, @FlorianBrinkmann if you open that zip in a text editor, these lines are at the top:

```
<b>Notice</b>:  Trying to get property of non-object in <b>/var/www/virtual/fbn/test.themes.florianbrinkmann.de/wp-content/plugins/eight-day-week-print-workflow/includes/functions/plugins/article-export.php</b> on line <b>519</b><br />
<br />
<b>Notice</b>:  Trying to get property of non-object in <b>/var/www/virtual/fbn/test.themes.florianbrinkmann.de/wp-content/plugins/eight-day-week-print-workflow/includes/functions/plugins/article-export.php</b> on line <b>523</b><br />
```

I think this points to the bug: the post author isn't an object. Do you have an author set on the post you're exporting?

**Comment by FlorianBrinkmann** [comment]
@sternb0t yes, there is an author set on the post. I tested the plugin on my productive site which is not running a development version of WordPress and there it works without problems, so it seems to be a problem with the WordPress alpha, not the plugin.

**Comment by sternb0t** [comment]
Ah ok that makes sense @FlorianBrinkmann. Thanks for the followup!
