### ISSUE TITLE
Test against WordPress 6.0

### ISSUE THREAD

**Issue by vikrampm1** [observermedia/eight-day-week#80]
Is your enhancement related to a problem? Please describe.
Once WordPress 6.0 is released, we'll want to test Eight Day Week to see if any incompatibility issues arise.

Describe the solution you'd like

- [x] test Eight Day Week on WordPress 6.0
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

Designs
n/a

Describe alternatives you've considered
None

Additional context
Related: #77, #65, #54, #19

**Comment by peterwilsoncc** [comment]
Testing notes

- [x] Install and activate plugin (checks activation hook)
- [x] Create issue status
- [x] Create publications
- [x] Create article statuses
- [x] Create an issue
- [x] Assign a publication
- [x] Assign an issue status
- [x] Add articles to issue
- [x] Modify article status
- [x] Ensure at least one article has images (this is to ensure they are REMOVED from export, as expected)
- [x] Export article
- [x] Export all articles
- [x] Save issue
- [x] Update issue status
- [x] Update publication
- [ ] Quick edit issue
- [x] Quick edit publication
- [x] Quick edit article status
- [x] Quick edit issue status
- [x] Edit publication
- [x] Edit article status
- [x] Edit issue status

Repeat article tests with the Co-Authors Plus plugin enabled.
