### ISSUE TITLE
Custom Post Types

### ISSUE THREAD

**Issue by Jared-Williams** [observermedia/eight-day-week#9]
I see that the current post_type is set to pull "posts". I was wondering if there was a way to extend this to support custom post types as well?

We organize some content through CPTs so being able to export those posts as well would be awesome!

**Comment by anthony-j-castro** [comment]
@Jared-Williams thanks for the suggestion! We just added the filter `Eight_Day_Week\Articles\post_types` that you can use.

Sample usage might look like:

```
add_filter( 'Eight_Day_Week\Articles\post_types', function( $default_post_types ) {
    return array_merge( $default_post_types, [ 'my_custom_post_type' ] );
} );
```

**Comment by Jared-Williams** [comment]
@anthony-j-castro Thanks for adding that! I just updated and used the filter for multiple post types. Works perfectly!
